# Generated by Django 3.1.4 on 2021-02-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foiling', '0002_dr_form_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr_form',
            name='approver',
            field=models.CharField(choices=[('ELIZABETH GAMIT', 'ELIZABETH GAMIT'), ('SENNA DEL VALLE', 'SENNA DEL VALLE')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dr_form',
            name='customer',
            field=models.CharField(choices=[('CHRYSLER', 'CHRYSLER'), ('GM', 'GM'), ('FORD', 'FORD')], max_length=50),
        ),
    ]
