# Generated by Django 3.1.4 on 2021-02-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foiling', '0003_auto_20210216_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr_form',
            name='customer',
            field=models.CharField(choices=[('CHRYSLER', 'CHRYSLER'), ('GM', 'GM'), ('FORD-14401-IP', 'FORD-14401-IP'), ('FORD-14405-FRAME', 'FORD-14405-FRAME')], max_length=50),
        ),
    ]
