# Generated by Django 3.1.4 on 2021-02-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komax', '0004_dr_form_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr_form',
            name='customer',
            field=models.CharField(choices=[('FORD', 'FORD'), ('HONDA', 'HONDA'), ('IMV', 'IMV'), ('GM', 'GM'), ('OUTLANDER', 'OUTLANDER'), ('CHRYSLER', 'CHRYSLER')], max_length=50),
        ),
    ]
